version: 0.2

phases:
  pre-build:
    commands:
      - npm install

  build:
    commands:
      - npm run test
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist