orbs:
  react: thefrontside/react@0.2.0
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
version: 2.1
workflows:
  build: 
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: myApplication
          bundle-bucket: myApplicationS3Bucket
          bundle-key: myS3BucketKey
          deployment-group: myDeploymentGroup
          service-role-arn: myDeploymentGroupRoleARN
     
