version: 0.2

phases:
    install:
        commands:
          - npm i


pre-build:
  commands:
      - npm

build:
  commands:
      - npm test
      - npm build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist